# Change these first
owner: jesusm0920 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Grupo Dimakers
    url: https://grupodimakers.com
  - name: IDM dev
    url: https://idmdev.tech
  - name: Puente
    url: https://apis.idmdev.tech
  - name: Delivery
    url: https://delivery-to.com/administrador/
  - name: AGSAL
    url: https://digital.aguasdesaltillo.com
  - name: WH Tools
    url: https://wh.tools
  - name: Aguillon
    url: https://aguillon.com.mx
  - name: Lennox Reclutamiento
    url: https://lennoxreclutamiento.com
  - name: Lennox Bot Reclutamiento
    url: https://bot.lennoxreclutamiento.com
  - name: Lennox Bot Salary
    url: https://botsalary.lennoxreclutamiento.com
  - name: Lennox Bot PTU
    url: https://lennoxforemployee.lennoxreclutamiento.com
  - name: Platinados
    url: https://platinados.platco.net
  - name: Plating
    url: https://plating.platco.net

assignees:
  - jesusm0920

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: pablokbs.github.io
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pages Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
